#include "test_support.inc"
/* clang-format off */
#include "test_protocol_framing.inc"
#include "test_parse_serialize.inc"
#include "test_array_stream.inc"
#include "test_array_rewrite.inc"
#include "test_fixtures_public.inc"
#include "test_json_value_sources.inc"
#include "test_allocator_visitor.inc"
#include "test_generator_omit.inc"
#include "test_writer.inc"
#include "test_value_rewrite.inc"
#include "test_curl_misc.inc"
/* clang-format on */

int main(void) {
  test_parse_implicit_destination_reset();
  test_dynamic_allocation_cleanup_balance();
  test_dynamic_allocation_reset_reparse_balance();
  test_clear_destination_false_present_arrays_replace();
  test_clear_destination_false_fixed_capacity_string_array_reuse_frees_replaced_entries();
  test_zero_alloc_validate_path();
  test_f64_boundary_exponents_stay_on_fast_path();
  test_f64_boundary_exponents_are_locale_independent();
  test_parser_workspace_accounting();
  test_parser_workspace_alignment_regression();
  test_init_does_not_preserve_garbage_array_state();
  test_zero_alloc_fixed_storage_parse();
  test_zero_alloc_fixed_storage_serialize();
  test_zero_alloc_jsonl_serialize();
  test_serialize_alloc_balance();
  test_serialize_owned_output_cap_is_enforced();
  test_serialize_owned_output_cap_allows_exact_payload();
  test_serialize_alloc_zero_cap_uses_safe_default();
  test_serialize_alloc_default_free_compatibility();
  test_serialize_jsonl_alloc_balance();
  test_serialize_jsonl_alloc_output_cap_is_enforced();
  test_serialize_alloc_pretty_output_cap_is_enforced();
  test_serialize_jsonl_alloc_default_free_compatibility();
  test_parse_buffer_basic();
  test_parse_fixed_strings_with_escapes_and_truncation();
  test_chunked_parser_and_missing_required();
  test_object_framed_stream_jsonl();
  test_stream_reuses_and_changes_destination();
  test_stream_reuse_fixed_capacity_string_array_frees_replaced_entries();
  test_object_stream_nonblocking_fd_would_block();
  test_array_stream_mapped_items_from_root_key();
  test_array_stream_raw_values_from_root_array();
  test_array_stream_open_path_and_fd_sources();
  test_array_stream_failure_modes();
  test_array_stream_streaming_invariants();
  test_array_stream_delimiter_validation_before_yield();
  test_array_stream_mapped_items_do_not_materialize_item();
  test_array_stream_skips_do_not_materialize_values();
  test_array_stream_escaped_key_path_matching();
  test_array_stream_escaped_key_failure_modes();
  test_array_stream_duplicate_rejection_invariants();
  test_array_stream_raw_duplicate_check_allows_large_values();
  test_array_stream_reader_tolerates_empty_reads();
  test_array_stream_additional_failure_modes();
  test_array_stream_would_block_boundaries();
  test_array_stream_depth_limit_and_argument_guards();
  test_array_stream_push_api();
  test_array_stream_push_invariant_failure_modes();
  test_array_stream_push_does_not_materialize_response();
  test_array_stream_push_cleans_reused_destination();
  test_array_stream_push_string_items();
  test_array_stream_push_string_item_callback();
  test_array_stream_push_string_item_callback_bounds();
  test_array_stream_push_string_failure_modes();
  test_array_stream_mapped_string_field_envelope();
  test_array_stream_mapped_string_field_metadata_and_long_item();
  test_array_stream_mapped_string_field_failure_modes();
  test_array_stream_mapped_string_field_serialize_rejected();
  test_array_stream_mapped_field_nested_items();
  test_array_stream_mapped_field_nested_json_value_sink_reuse();
  test_array_stream_mapped_field_failure_modes();
  test_array_stream_mapped_field_failure_cleans_alloc_items();
  test_array_stream_mapped_field_curl_facade();
  test_array_stream_mapped_string_field_curl_facade();
  test_array_rewrite_root_array_mapped_actions();
  test_array_rewrite_direct_and_nested_arrays();
  test_array_rewrite_parent_context_filters_nested_array();
  test_array_rewrite_repeated_parent_segments();
  test_array_rewrite_json_value_items_and_failures();
  test_array_rewrite_callback_and_action_failures();
  test_array_rewrite_argument_and_selector_failures();
  test_array_rewrite_parse_type_and_reader_failures();
  test_array_rewrite_string_capture_allocation_failures();
  test_array_rewrite_reader_uses_configured_allocator();
  test_array_rewrite_reader_allocator_failure();
  test_array_rewrite_item_parse_and_limit_failures();
  test_array_rewrite_source_and_parent_failures();
  test_array_rewrite_append_only_and_object_path();
  test_array_rewrite_empty_all_drop_and_all_append();
  test_array_rewrite_append_only_root_zero_alloc();
  test_array_rewrite_spooled_replacement_item();
  test_array_rewrite_large_array_memory_bound();
  test_array_rewrite_owned_item_cleanup_between_items();
  test_array_rewrite_truncation_status_is_preserved();
  test_array_rewrite_owned_parent_cleanup_between_parents();
  test_array_rewrite_owned_item_cleanup_on_failures();
  test_array_rewrite_owned_parent_cleanup_on_failures();
  test_array_rewrite_path_helper();
  test_array_rewrite_helper_failures();
  test_array_rewrite_fd_to_fd_helper();
  test_file_and_buffer_helpers();
  test_jsonl_helpers();
  test_sse_incremental_events_and_json_selection();
  test_sse_json_streams_data_without_event_buffering();
  test_sse_json_event_limits_and_boundary_errors();
  test_sse_json_event_limits_alloc_guarded_e2e();
  test_sse_retry_and_json_metadata_only_events();
  test_sse_callback_failure_status();
  test_sse_limits_and_allocation_contract();
  test_sse_limits_and_invalid_usage();
  test_multipart_incremental_parts_and_raw_payloads();
  test_multipart_no_length_preserves_body_bytes();
  test_multipart_no_length_streams_long_lines_with_lookahead();
  test_multipart_content_length_streams_body_without_body_allocations();
  test_multipart_content_disposition_name_parameters();
  test_multipart_limits_and_invalid_usage();
  test_multipart_failures_are_reported();
  test_fixed_capacity_object_array();
  test_dynamic_object_array_alignment();
  test_formatting_variants_and_roundtrip();
  test_duplicate_key_policy();
  test_public_api_argument_and_serialization_guards();
  test_public_initializers_and_defaults();
  test_nullable_presence_primitives();
  test_nullable_presence_primitive_failures();
  test_small_valid_spec_fixtures();
  test_invalid_json_vectors();
  test_fixture_documents();
  test_large_generated_fixture_sizes();
  test_large_generated_fixture_parsing();
  test_json_test_suite_parsing();
  test_spooled_fields_roundtrip();
  test_spooled_fields_small_and_null();
  test_spooled_append_api();
  test_spooled_field_failures();
  test_source_fields_path_and_raw_sink();
  test_source_fields_file_and_fd();
  test_source_field_parse_and_seek_failures();
  test_source_fields_do_not_mutate_sink_on_open_failure();
  test_json_value_parse_and_roundtrip();
  test_json_value_parse_capture_escapes();
  test_json_value_parse_stream_sink();
  test_json_value_nested_object_parse_sink_and_reuse();
  test_json_value_nested_object_parse_sink_failure_matrix();
  test_json_value_parse_visitor();
  test_json_value_nested_object_parse_visitor();
  test_json_value_parse_visitor_fast_path_regressions();
  test_json_value_parse_visitor_total_byte_reset_for_string_regressions();
  test_json_value_parse_visitor_scalar_string_regressions();
  test_json_value_setters_and_failures();
  test_json_value_scalars_null_and_reset();
  test_json_value_nested_object_parse_capture();
  test_json_value_large_string_scalar_regressions();
  test_json_value_large_string_object_regressions();
  test_json_value_large_string_nested_regressions();
  test_json_value_reuse_and_cleanup_ownership();
  test_json_value_source_validation_failures();
  test_json_value_nonseekable_and_sink_failures();
  test_json_value_large_source_backed_serialization();
  test_json_value_parse_requires_destination_and_partial_failure();
  test_json_value_nested_failure_matrix();
  test_value_visitor_success_and_limits();
  test_value_visitor_chunking_unicode_and_failures();
  test_custom_allocator_parse_cleanup_and_stream();
#ifndef NDEBUG
  test_custom_allocator_misaligned_owned_alloc_is_rejected();
#endif
  test_custom_allocator_json_value_capture_and_serialize_alloc();
  test_custom_allocator_raw_serialize_alloc_is_rejected();
  test_explicit_default_allocator_raw_serialize_alloc_is_allowed();
  test_explicit_default_allocator_raw_serialize_jsonl_alloc_is_allowed();
  test_custom_allocator_json_value_capture_preserves_handle_allocator();
  test_partial_allocator_parse_is_rejected();
  test_partial_allocator_parse_reader_is_rejected();
  test_partial_allocator_serialize_alloc_is_rejected();
  test_partial_allocator_generator_init_is_rejected();
  test_generator_compact_streams_event_map();
  test_generator_pretty_streams_source_field();
  test_generator_streams_json_value_fields();
  test_generator_pretty_streams_json_value_reader();
  test_writer_dynamic_object_and_values();
  test_writer_primitive_string_sources();
  test_writer_invalid_state_and_sink_failure();
  test_writer_number_text_rejects_non_numbers();
  test_writer_value_stream_success_and_commas();
  test_writer_value_stream_root_scalars();
  test_writer_value_stream_failure_modes();
  test_writer_value_stream_state_and_sink_failures();
  test_writer_json_value_helpers_sources();
  test_writer_json_value_spooled_preserves_spill_cursor();
  test_writer_json_value_helpers_failure_modes();
  test_writer_array_items_helpers_sources();
  test_writer_array_items_spooled_preserves_spill_cursor();
  test_writer_array_items_helpers_failure_modes();
  test_writer_child_sink_failures();
  test_writer_generator_streams_producer();
  test_writer_generator_zero_capacity_read();
  test_writer_generator_primitive_scalars_resume();
  test_writer_generator_matches_sink_under_backpressure();
  test_writer_generator_preserves_event_state_on_backpressure();
  test_writer_generator_rejects_retry_mismatch();
  test_writer_generator_rejects_child_retry_mismatch();
  test_writer_generator_backpressure_matrix();
  test_writer_generator_streams_source_without_materializing();
  test_writer_generator_streams_json_value_without_materializing();
  test_writer_generator_streams_mapped_without_materializing();
  test_writer_generator_string_reader_preserves_chunks();
  test_value_rewrite_replace_drop_and_root();
  test_value_rewrite_callback_replacement();
  test_value_rewrite_replace_with_and_buffer_adapters();
  test_value_rewrite_replace_with_old_value_metadata();
  test_value_rewrite_replace_with_callback_failures();
  test_value_rewrite_old_value_visitor_balanced_events();
  test_value_rewrite_old_value_visitor_failures();
  test_value_rewrite_adapter_and_sink_failures();
  test_value_rewrite_selector_and_source_base64();
  test_value_rewrite_missing_object_path_and_streaming_string();
  test_value_rewrite_failures();
  test_serialize_omits_empty_optional_fields();
  test_serialize_omit_layout_failures();
  test_serialize_omit_pretty_and_recursive_invariants();
  test_serialize_omit_empty_implies_null();
  test_serialize_declarative_conditional_helpers();
  test_rewindability_edges_and_measure_preserves_sources();
#ifdef LONEJSON_WITH_CURL
  test_curl_upload_cleanup_default_allocator();
  test_curl_upload_custom_allocator_balance();
  test_curl_upload_streaming_does_not_buffer_payload();
  test_curl_array_parse_streams_selected_arrays();
  test_curl_array_parse_failure_cleanup_and_truncation();
  test_curl_string_array_parse_streams_keys();
  test_curl_string_items_parse_streams_keys();
#endif
  test_clear_destination_ignores_poisoned_stream_and_json_value_state();
  test_prepared_fixed_object_array_parse_preserves_storage();

  if (g_failures != 0) {
    fprintf(stderr, "test failures: %d\n", g_failures);
    return 1;
  }
  return 0;
}
