upstream lonejson_sink {
    server sink:9000;
}

server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /variants/ {
        try_files $uri =404;
    }

    location /generated/ {
        alias /usr/share/nginx/generated/;
        try_files $uri =404;
    }

    location /ingest {
        proxy_pass http://lonejson_sink;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 8443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    root /usr/share/nginx/html;
    index index.html;

    location /variants/ {
        try_files $uri =404;
    }

    location /generated/ {
        alias /usr/share/nginx/generated/;
        try_files $uri =404;
    }

    location /ingest {
        proxy_pass http://lonejson_sink;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
