set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER /usr/bin/musl-gcc CACHE FILEPATH "")

set(LONEJSON_TARGET_ARCH x86_64 CACHE STRING "" FORCE)
set(LONEJSON_TARGET_OS linux CACHE STRING "" FORCE)
set(LONEJSON_TARGET_LIBC musl CACHE STRING "" FORCE)
