if(NOT DEFINED LONEJSON_COMPILE_COMMANDS)
  message(FATAL_ERROR "LONEJSON_COMPILE_COMMANDS is required")
endif()
if(NOT DEFINED LONEJSON_SOURCE_FILE)
  message(FATAL_ERROR "LONEJSON_SOURCE_FILE is required")
endif()
if(NOT DEFINED LONEJSON_AFL_COMPILER)
  message(FATAL_ERROR "LONEJSON_AFL_COMPILER is required")
endif()

file(READ "${LONEJSON_COMPILE_COMMANDS}" LONEJSON_COMPILE_COMMANDS_JSON)

string(JSON LONEJSON_COMMAND_COUNT LENGTH "${LONEJSON_COMPILE_COMMANDS_JSON}")
math(EXPR LONEJSON_LAST_COMMAND "${LONEJSON_COMMAND_COUNT} - 1")
set(LONEJSON_FOUND_SOURCE OFF)

foreach(LONEJSON_INDEX RANGE 0 ${LONEJSON_LAST_COMMAND})
  string(JSON LONEJSON_COMMAND_FILE GET "${LONEJSON_COMPILE_COMMANDS_JSON}"
         ${LONEJSON_INDEX} file)
  if(LONEJSON_COMMAND_FILE STREQUAL LONEJSON_SOURCE_FILE)
    set(LONEJSON_FOUND_SOURCE ON)
    string(JSON LONEJSON_COMMAND GET "${LONEJSON_COMPILE_COMMANDS_JSON}"
           ${LONEJSON_INDEX} command)
    string(FIND "${LONEJSON_COMMAND}" "${LONEJSON_AFL_COMPILER}"
                LONEJSON_AFL_COMPILER_INDEX)
    string(FIND "${LONEJSON_COMMAND}" "-fsanitize=fuzzer"
                LONEJSON_LEGACY_FUZZER_INDEX)
    if(NOT LONEJSON_AFL_COMPILER_INDEX LESS 0 AND
       LONEJSON_LEGACY_FUZZER_INDEX LESS 0)
      return()
    endif()
  endif()
endforeach()

if(NOT LONEJSON_FOUND_SOURCE)
  message(FATAL_ERROR
          "compile_commands.json does not contain ${LONEJSON_SOURCE_FILE}")
endif()

message(FATAL_ERROR
        "fuzz build does not contain an instrumented ${LONEJSON_SOURCE_FILE}; "
        "expected the pinned AFL++ GCC wrapper ${LONEJSON_AFL_COMPILER}")
