include("${CMAKE_CURRENT_LIST_DIR}/c_pkt_systems_metadata.cmake")
file(READ "${LONEJSON_MANIFEST}" manifest)
function(expect_json expected label)
  string(JSON actual ERROR_VARIABLE error GET "${manifest}" ${ARGN})
  if(error OR NOT "${actual}" STREQUAL "${expected}")
    message(FATAL_ERROR "dependency manifest mismatch: ${label}")
  endif()
endfunction()
expect_json("pkt.systems.dependencies.v1" schema schema)
expect_json(lonejson project project)
if(DEFINED LONEJSON_VERSION)
  expect_json("${LONEJSON_VERSION}" version version)
endif()
expect_json("${LONEJSON_TARGET_ID}" target_id target_id)
string(JSON count LENGTH "${manifest}" dependencies)
if(NOT count EQUAL 3)
  message(FATAL_ERROR "dependency manifest must describe the SDK input and both external facades")
endif()
lonejson_c_pkt_systems_sha256("${LONEJSON_TARGET_ID}" sha256)
set(archive "c.pkt.systems-${LONEJSON_C_PKT_SYSTEMS_PINNED_VERSION}-${LONEJSON_TARGET_ID}.tar.gz")
set(names c.pkt.systems curl openssl)
set(versions "${LONEJSON_C_PKT_SYSTEMS_PINNED_VERSION}" "${LONEJSON_C_PKT_SYSTEMS_CURL_VERSION}" "${LONEJSON_C_PKT_SYSTEMS_OPENSSL_VERSION}")
set(licenses MIT curl Apache-2.0)
foreach(index RANGE 0 2)
  list(GET names ${index} name)
  list(GET versions ${index} version)
  list(GET licenses ${index} license)
  expect_json("${name}" "${name}.name" dependencies ${index} name)
  expect_json("${version}" "${name}.version" dependencies ${index} version)
  expect_json("${license}" "${name}.license" dependencies ${index} license)
  expect_json("${LONEJSON_TARGET_ID}" "${name}.target_id" dependencies ${index} target_id)
  expect_json("${archive}" "${name}.archive_name" dependencies ${index} archive_name)
  expect_json("${LONEJSON_C_PKT_SYSTEMS_BASE_URL_DEFAULT}/${archive}" "${name}.source_url" dependencies ${index} source_url)
  expect_json("${sha256}" "${name}.sha256" dependencies ${index} sha256)
  expect_json(OFF "${name}.bundled" dependencies ${index} bundled)
  if(index EQUAL 0)
    expect_json(OFF "${name}.external" dependencies ${index} external)
    expect_json("GitHub release" "${name}.source_system" dependencies ${index} source_system)
    expect_json(release-sdk-build-input "${name}.role" dependencies ${index} role)
    expect_json(curl "${name}.provides.curl" dependencies ${index} provides 0)
    expect_json(openssl "${name}.provides.openssl" dependencies ${index} provides 1)
  else()
    expect_json(ON "${name}.external" dependencies ${index} external)
    expect_json(c.pkt.systems "${name}.source_system" dependencies ${index} source_system)
    expect_json(optional-facade-consumer-requirement "${name}.role" dependencies ${index} role)
  endif()
endforeach()
